spring:
  application:
    name: dada-be

  data:
    mongodb:
      connection-string: mongodb://localhost:27017/dada

server:
  port: 8080
  error:
    include-message: always


springdoc:
  # ?? API? ?? ?? ??? JSON?? ?? (Orval Blob ?? ?? ??)
  default-produces-media-type: application/json
  # Swagger UI?? JSON ??? ???? ???
  writer-with-default-pretty-printer: true
  swagger-ui:
    path: /swagger-ui.html
    # API ?? ?? ??? ?????? (??? ??)
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs